clair:
  database:
    type: pgsql
    options:
      source: postgresql://username:password@postgres:5432/clair?sslmode=disable
      cachesize: 16384
  api:
    port: 6060
    healthport: 6061
    timeout: 900s
  updater:
    interval: 2h
  notifier:
    attempts: 3
    renotifyinterval: 2h
  verifier_proxies:
  - enabled: true
    # The port at which Clair will listen.
    listen_addr: :6060
