version: '3'
services:
  database:
    image: 'postgres:14-alpine'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username 
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: clair 
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
  clair:
    image: quay.io/coreos/clair:v4.2.3
    restart: unless-stopped
    volumes:
      - ./docker-compose-data/clair-config/:/config/:ro
      - ./docker-compose-data/clair-tmp/:/tmp/:rw
    depends_on: 
      - "database"
    command: ["./wait-for-it.sh", "database:5432", "--", "-conf", "/config/config.yml"]
    user: root

  clairctl:
    image: jgsqware/clairctl:latest
    restart: unless-stopped
    environment: 
      - DOCKER_API_VERSION=1.41
    volumes:
      - ./docker-compose-data/clairctl-reports/:/reports/:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on: 
      - "clair" 
    user: root
